name: Musl Repository Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    # Quitamos el 'container:' global para que Actions use el entorno de Ubuntu nativo

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies (Rsync & SSHpass)
        run: sudo apt-get update && sudo apt-get install -y sshpass rsync

      - name: Clone void-packages and templates
        run: |
          git clone --depth 1 https://codeberg.org/Neko-Void/musl-repo.git /tmp/srcpkgs
          git clone --depth 1 https://github.com/void-linux/void-packages.git /tmp/void-packages
          # Copiamos el contenido dentro de la carpeta srcpkgs existente
          cp -rf /tmp/srcpkgs/* /tmp/void-packages/srcpkgs/
          echo "#nnothing" >> /tmp/void-packages/common/build-style/none.sh

      - name: Download existing repo from SourceForge
        env:
          SFTP_USER: ${{ secrets.SFTP_USERNAME }}
          SSHPASS: ${{ secrets.SFTP_PASSWORD }}
        run: |
          mkdir -p /tmp/void-packages/hostdir/binpkgs
          cd /tmp/void-packages/hostdir/binpkgs
          sshpass -e rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ${SFTP_USER}@frs.sourceforge.net:/home/frs/project/neko-void/repo/musl .

      - name: Build and Sign packages in Void Musl Container
        env:
          XBPS_PRIVKEY: ${{ secrets.XBPS_PRIVATE_KEY }}
        run: |
          echo "$XBPS_PRIVKEY" > /tmp/void-packages/privkey.pem
          
          docker run --rm --privileged -v /tmp/void-packages:/void-packages ghcr.io/void-linux/void-musl:latest /bin/sh -c "
            xbps-install -Syu xbps && xbps-install -Syu && \
            xbps-install -y base-devel xtools tar gcc make shadow util-linux && \
            useradd -m builder && \
            chown -R builder:builder /void-packages && \
            
            chroot --userspec=builder:builder / bash -c 'cd /void-packages && ./xbps-src binary-bootstrap' && \
            chroot --userspec=builder:builder / bash -c 'cd /void-packages && ./xbps-src pkg Neko-Wizard' && \
            chroot --userspec=builder:builder / bash -c 'cd /void-packages && ./xbps-src pkg kasha-installer' && \
            chroot --userspec=builder:builder / bash -c 'cd /void-packages && ./xbps-src pkg neko-icons' && \
            chroot --userspec=builder:builder / bash -c 'cd /void-packages && ./xbps-src pkg neko-themes' && \
            chroot --userspec=builder:builder / bash -c 'cd /void-packages && ./xbps-src pkg neko-backgrounds' && \
            
            cd /void-packages/hostdir/binpkgs && \
            xbps-rindex --sign-pkg --privkey /void-packages/privkey.pem *.xbps && \
            xbps-rindex -a *.xbps && \
            xbps-rindex --sign --signedby 'javierc' --privkey /void-packages/privkey.pem . && \
            
            chmod -R 777 /void-packages/hostdir/binpkgs
          "
          
          # Adding sudo to force removal despite changed ownership
          sudo rm -f /tmp/void-packages/privkey.pem
          
      - name: Deploy to SourceForge
        env:
          SFTP_USER: ${{ secrets.SFTP_USERNAME }}
          SSHPASS: ${{ secrets.SFTP_PASSWORD }}
        run: |
          cd /tmp/void-packages/hostdir/binpkgs
          sshpass -e rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" . ${SFTP_USER}@frs.sourceforge.net:/home/frs/project/neko-void/repo/musl/
